In [1]:
import numpy as np

## Basics/Arrays

In [2]:
a = np.array([1,2,3]) # 1d array
a

array([1, 2, 3])

In [3]:
b = np.array([[9.0,5.4,2.1],[6.4,6.6,31.1]]) # 2d array
b

array([[ 9. ,  5.4,  2.1],
       [ 6.4,  6.6, 31.1]])

In [4]:
# get dimension
a.ndim

1

In [5]:
# get shape
b.shape

(2, 3)

In [6]:
# get type
a.dtype

dtype('int32')

In [7]:
# get size
a.itemsize

4

In [8]:
# changing type changes size (from 32 to 16 here)
a = np.array([1,2,3],dtype="int16")

In [9]:
# get size
a.itemsize

2

In [10]:
# get total size
a.nbytes
#or
a.size * a.itemsize

6

## Accesing/changing elements, rows, columns etc.

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [12]:
# get element [r, c]
a[1, 5]

13

In [13]:
# get row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# get column
a[:,4]

array([ 5, 12])

In [15]:
# more specific with 'step' [startindex:endindex:stepsize]
# from 2 to 6 with step of every other one
a[0, 1:6:2]

array([2, 4, 6])

In [16]:
# change element
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [17]:
# changing a whole column to 5's
a[:,2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [18]:
# 3d array
b = np.array([[[2,3],[3,4]],[[5,6],[7,8]]])
b

array([[[2, 3],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
# select from 3d (work outside-in) Select: 6
b[1,0,1]

6

In [20]:
# replace 6 with 9 :)
b[1,0,1] = 9
b

array([[[2, 3],
        [3, 4]],

       [[5, 9],
        [7, 8]]])

## Initializing different types of arrays.

In [21]:
# 0 matrixes (sets of sets,sets,row,columns)
# 3 sets of 2 sets consisting of 3 by 4 matrixes
np.zeros((3,2,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [22]:
# 1 matrixes
# 4 sets of 2 by 2
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [23]:
# any other number ((x by y), of value)
# 2 by 2 filled with 99
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [24]:
# fill an already known matrix (a from the beggining of the notebook here)
np.full_like(a, 4)
# or
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
# random decimals
np.random.rand(4,2,3)

array([[[0.92674653, 0.81530239, 0.49316401],
        [0.17425837, 0.93513076, 0.74143486]],

       [[0.02532426, 0.57462217, 0.77131808],
        [0.59006261, 0.3105784 , 0.99790871]],

       [[0.88260222, 0.41016678, 0.04204859],
        [0.31990314, 0.38316994, 0.71237119]],

       [[0.54733915, 0.50435856, 0.9237132 ],
        [0.86658132, 0.99763003, 0.86700099]]])

In [26]:
# random integers (from 4 up to 9, with size 3by3)
np.random.randint(4,10, size=(3,3))

array([[9, 4, 7],
       [5, 8, 9],
       [9, 4, 6]])

In [27]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# building a FUNNY array
x = np.ones((5,5))
z = np.zeros((3,3))
z[1,1]=9
x[1:-1,1:4] = z # -1 means to the end

In [29]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

##### how to copy without changing values

In [30]:
# bad
a = np.array([1,2,3])
b = a
b[0]=420
print(a)
print(b)

[420   2   3]
[420   2   3]


In [31]:
#good
a = np.array([1,2,3])
b = a.copy()
b[0]=420
print(a)
print(b)

[1 2 3]
[420   2   3]


## Mathematics

In [32]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [33]:
b = np.array([1,0,1,0])
b

array([1, 0, 1, 0])

In [34]:
a + 2

array([3, 4, 5, 6])

In [35]:
a-2

array([-1,  0,  1,  2])

In [36]:
a * 2

array([2, 4, 6, 8])

In [37]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [38]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [39]:
a+b

array([2, 2, 4, 4])

In [40]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Linear Algebra

In [41]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
b = np.full((3,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [43]:
# np matrix multiply (a,b)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [44]:
# finding det
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.linalg.det(c)

1.0

## Statistics

In [46]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.min(stats)

1

In [48]:
np.min(stats, axis=0)

array([1, 2, 3])

In [49]:
np.sum(stats)

21

In [50]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [51]:
before = np.array([[1,2,3,4],[4,5,6,7]])
before

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [52]:
# reshaping, values must fit
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [53]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

# verticall stacking
np.vstack([v1,v2,v1,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [54]:
# horizontal stack
np.hstack([v1,v2,v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

## Misc

In [55]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[ 1., 20.,  3.,  5.,  7.,  9., 55., 33., 78., 13., 78.],
       [11., 56., 32., 82., 15., 85., 13., 75., 23., 12., 63.],
       [ 5.,  6.,  7.,  8., 64., 11.,  9., 54., 99.,  9.,  2.]])

## Boolean Masking and Advanced Indexing

In [56]:
filedata[filedata > 25]

array([55., 33., 78., 78., 56., 32., 82., 85., 75., 63., 64., 54., 99.])

In [57]:
# is any number in columns greater than 25?
np.any(filedata > 25, axis = 0)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True])

In [58]:
# are all numbers in a certain row greater than 0?
np.all(filedata > 10, axis = 0)

array([False, False, False, False, False, False, False,  True,  True,
       False, False])

In [59]:
((filedata > 25) & (filedata < 99))

array([[False, False, False, False, False, False,  True,  True,  True,
        False,  True],
       [False,  True,  True,  True, False,  True, False,  True, False,
        False,  True],
       [False, False, False, False,  True, False, False,  True, False,
        False, False]])